// Generated by purs bundle 0.14.5
var PS = {};
(function(exports) {
  "use strict";

  exports.log = function (s) {
    return function () {
      console.log(s);
    };
  };
})(PS["Effect.Console"] = PS["Effect.Console"] || {});
(function($PS) {
  // Generated by purs version 0.14.5
  "use strict";
  $PS["Effect.Console"] = $PS["Effect.Console"] || {};
  var exports = $PS["Effect.Console"];
  var $foreign = $PS["Effect.Console"];
  exports["log"] = $foreign.log;
})(PS);
(function($PS) {
  "use strict";
  $PS["Main"] = $PS["Main"] || {};
  var exports = $PS["Main"];
  var Effect_Console = $PS["Effect.Console"];                
  var myApi = function (x) {
      return function (y) {
          return x > 5 && y !== "Hello";
      };
  };
  var main = Effect_Console.log("Hello");
  exports["main"] = main;
  exports["myApi"] = myApi;
})(PS);
module.exports = PS["Main"];
