/* eslint-disable */

export const AllTypesProps: Record<string,any> = {
	Query:{
		names:{
			filter:{
				type:"names_filter",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			page:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			search:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		names_by_id:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		names_aggregated:{
			groupBy:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:false
			},
			filter:{
				type:"names_filter",
				array:false,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			search:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:false
			}
		},
		views:{
			filter:{
				type:"views_filter",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			page:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			search:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		views_by_id:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		views_aggregated:{
			groupBy:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:false
			},
			filter:{
				type:"views_filter",
				array:false,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			search:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:false
			}
		},
		views_translations:{
			filter:{
				type:"views_translations_filter",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			page:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			search:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		views_translations_by_id:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		views_translations_aggregated:{
			groupBy:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:false
			},
			filter:{
				type:"views_translations_filter",
				array:false,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			search:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:false
			}
		},
		languages:{
			filter:{
				type:"languages_filter",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			page:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			search:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		languages_by_id:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			}
		}
	},
	names_filter:{
		id:{
			type:"number_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		_and:{
			type:"names_filter",
			array:true,
			arrayRequired:false,
			required:false
		},
		_or:{
			type:"names_filter",
			array:true,
			arrayRequired:false,
			required:false
		}
	},
	number_filter_operators:{
		_eq:{
			type:"Float",
			array:false,
			arrayRequired:false,
			required:false
		},
		_neq:{
			type:"Float",
			array:false,
			arrayRequired:false,
			required:false
		},
		_in:{
			type:"Float",
			array:true,
			arrayRequired:false,
			required:false
		},
		_nin:{
			type:"Float",
			array:true,
			arrayRequired:false,
			required:false
		},
		_gt:{
			type:"Float",
			array:false,
			arrayRequired:false,
			required:false
		},
		_gte:{
			type:"Float",
			array:false,
			arrayRequired:false,
			required:false
		},
		_lt:{
			type:"Float",
			array:false,
			arrayRequired:false,
			required:false
		},
		_lte:{
			type:"Float",
			array:false,
			arrayRequired:false,
			required:false
		},
		_null:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		_nnull:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	string_filter_operators:{
		_eq:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_neq:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_contains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_ncontains:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_starts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_nstarts_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_ends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_nends_with:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_in:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:false
		},
		_nin:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:false
		},
		_null:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		_nnull:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		_empty:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		_nempty:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	JSON: "String",
	views:{
		user_created:{
			filter:{
				type:"directus_users_filter",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			page:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			search:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		user_updated:{
			filter:{
				type:"directus_users_filter",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			page:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			search:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		name:{
			filter:{
				type:"names_filter",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			page:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			search:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		translations:{
			filter:{
				type:"views_translations_filter",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			page:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			search:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	directus_users:{
		avatar:{
			filter:{
				type:"directus_files_filter",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			page:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			search:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		role:{
			filter:{
				type:"directus_roles_filter",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			page:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			search:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	directus_files:{
		folder:{
			filter:{
				type:"directus_folders_filter",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			page:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			search:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		uploaded_by:{
			filter:{
				type:"directus_users_filter",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			page:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			search:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		modified_by:{
			filter:{
				type:"directus_users_filter",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			page:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			search:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	directus_folders:{
		parent:{
			filter:{
				type:"directus_folders_filter",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			page:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			search:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	directus_folders_filter:{
		id:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		parent:{
			type:"directus_folders_filter",
			array:false,
			arrayRequired:false,
			required:false
		},
		_and:{
			type:"directus_folders_filter",
			array:true,
			arrayRequired:false,
			required:false
		},
		_or:{
			type:"directus_folders_filter",
			array:true,
			arrayRequired:false,
			required:false
		}
	},
	directus_users_filter:{
		id:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		first_name:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		last_name:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		email:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		password:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		location:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		title:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		description:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		tags:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		avatar:{
			type:"directus_files_filter",
			array:false,
			arrayRequired:false,
			required:false
		},
		language:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		theme:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		tfa_secret:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		status:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		role:{
			type:"directus_roles_filter",
			array:false,
			arrayRequired:false,
			required:false
		},
		token:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		last_access:{
			type:"date_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		last_access_func:{
			type:"datetime_function_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		last_page:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		provider:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		external_identifier:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		auth_data:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		email_notifications:{
			type:"boolean_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		_and:{
			type:"directus_users_filter",
			array:true,
			arrayRequired:false,
			required:false
		},
		_or:{
			type:"directus_users_filter",
			array:true,
			arrayRequired:false,
			required:false
		}
	},
	directus_files_filter:{
		id:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		storage:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		filename_disk:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		filename_download:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		title:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		type:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		folder:{
			type:"directus_folders_filter",
			array:false,
			arrayRequired:false,
			required:false
		},
		uploaded_by:{
			type:"directus_users_filter",
			array:false,
			arrayRequired:false,
			required:false
		},
		uploaded_on:{
			type:"date_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		uploaded_on_func:{
			type:"datetime_function_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		modified_by:{
			type:"directus_users_filter",
			array:false,
			arrayRequired:false,
			required:false
		},
		modified_on:{
			type:"date_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		modified_on_func:{
			type:"datetime_function_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		charset:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		filesize:{
			type:"number_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		width:{
			type:"number_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		height:{
			type:"number_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		duration:{
			type:"number_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		embed:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		description:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		location:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		tags:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		metadata:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		_and:{
			type:"directus_files_filter",
			array:true,
			arrayRequired:false,
			required:false
		},
		_or:{
			type:"directus_files_filter",
			array:true,
			arrayRequired:false,
			required:false
		}
	},
	date_filter_operators:{
		_eq:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_neq:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_gt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_gte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_lt:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_lte:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		_null:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		_nnull:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	datetime_function_filter_operators:{
		year:{
			type:"number_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		month:{
			type:"number_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		week:{
			type:"number_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		day:{
			type:"number_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		weekday:{
			type:"number_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		hour:{
			type:"number_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		minute:{
			type:"number_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		second:{
			type:"number_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	directus_roles_filter:{
		id:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		icon:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		description:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		ip_access:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		enforce_tfa:{
			type:"boolean_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		admin_access:{
			type:"boolean_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		app_access:{
			type:"boolean_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		users:{
			type:"directus_users_filter",
			array:false,
			arrayRequired:false,
			required:false
		},
		_and:{
			type:"directus_roles_filter",
			array:true,
			arrayRequired:false,
			required:false
		},
		_or:{
			type:"directus_roles_filter",
			array:true,
			arrayRequired:false,
			required:false
		}
	},
	boolean_filter_operators:{
		_eq:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		_neq:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		_null:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		_nnull:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	Date: "String",
	directus_roles:{
		users:{
			filter:{
				type:"directus_users_filter",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			page:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			search:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	views_translations:{
		views_id:{
			filter:{
				type:"views_filter",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			page:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			search:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		},
		languages_id:{
			filter:{
				type:"languages_filter",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			page:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			search:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			}
		}
	},
	views_filter:{
		user_created:{
			type:"directus_users_filter",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_updated:{
			type:"directus_users_filter",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		status:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		sort:{
			type:"number_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		date_created:{
			type:"date_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		date_created_func:{
			type:"datetime_function_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		date_updated:{
			type:"date_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		date_updated_func:{
			type:"datetime_function_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		enum:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"names_filter",
			array:false,
			arrayRequired:false,
			required:false
		},
		translations:{
			type:"views_translations_filter",
			array:false,
			arrayRequired:false,
			required:false
		},
		_and:{
			type:"views_filter",
			array:true,
			arrayRequired:false,
			required:false
		},
		_or:{
			type:"views_filter",
			array:true,
			arrayRequired:false,
			required:false
		}
	},
	views_translations_filter:{
		id:{
			type:"number_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		views_id:{
			type:"views_filter",
			array:false,
			arrayRequired:false,
			required:false
		},
		languages_id:{
			type:"languages_filter",
			array:false,
			arrayRequired:false,
			required:false
		},
		foo:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		_and:{
			type:"views_translations_filter",
			array:true,
			arrayRequired:false,
			required:false
		},
		_or:{
			type:"views_translations_filter",
			array:true,
			arrayRequired:false,
			required:false
		}
	},
	languages_filter:{
		code:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"string_filter_operators",
			array:false,
			arrayRequired:false,
			required:false
		},
		_and:{
			type:"languages_filter",
			array:true,
			arrayRequired:false,
			required:false
		},
		_or:{
			type:"languages_filter",
			array:true,
			arrayRequired:false,
			required:false
		}
	},
	Mutation:{
		create_names_items:{
			filter:{
				type:"names_filter",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			page:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			search:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			data:{
				type:"create_names_input",
				array:true,
				arrayRequired:false,
				required:true
			}
		},
		create_names_item:{
			data:{
				type:"create_names_input",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		create_views_items:{
			filter:{
				type:"views_filter",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			page:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			search:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			data:{
				type:"create_views_input",
				array:true,
				arrayRequired:false,
				required:true
			}
		},
		create_views_item:{
			data:{
				type:"create_views_input",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		create_views_translations_items:{
			filter:{
				type:"views_translations_filter",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			page:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			search:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			data:{
				type:"create_views_translations_input",
				array:true,
				arrayRequired:false,
				required:true
			}
		},
		create_views_translations_item:{
			data:{
				type:"create_views_translations_input",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		create_languages_items:{
			filter:{
				type:"languages_filter",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			page:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			search:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			data:{
				type:"create_languages_input",
				array:true,
				arrayRequired:false,
				required:true
			}
		},
		create_languages_item:{
			data:{
				type:"create_languages_input",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		update_names_items:{
			filter:{
				type:"names_filter",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			page:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			search:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			ids:{
				type:"ID",
				array:true,
				arrayRequired:false,
				required:true
			},
			data:{
				type:"update_names_input",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		update_names_item:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			},
			data:{
				type:"update_names_input",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		update_views_items:{
			filter:{
				type:"views_filter",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			page:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			search:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			ids:{
				type:"ID",
				array:true,
				arrayRequired:false,
				required:true
			},
			data:{
				type:"update_views_input",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		update_views_item:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			},
			data:{
				type:"update_views_input",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		update_views_translations_items:{
			filter:{
				type:"views_translations_filter",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			page:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			search:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			ids:{
				type:"ID",
				array:true,
				arrayRequired:false,
				required:true
			},
			data:{
				type:"update_views_translations_input",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		update_views_translations_item:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			},
			data:{
				type:"update_views_translations_input",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		update_languages_items:{
			filter:{
				type:"languages_filter",
				array:false,
				arrayRequired:false,
				required:false
			},
			sort:{
				type:"String",
				array:true,
				arrayRequired:false,
				required:false
			},
			limit:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			offset:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			page:{
				type:"Int",
				array:false,
				arrayRequired:false,
				required:false
			},
			search:{
				type:"String",
				array:false,
				arrayRequired:false,
				required:false
			},
			ids:{
				type:"ID",
				array:true,
				arrayRequired:false,
				required:true
			},
			data:{
				type:"update_languages_input",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		update_languages_item:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			},
			data:{
				type:"update_languages_input",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		delete_names_items:{
			ids:{
				type:"ID",
				array:true,
				arrayRequired:false,
				required:true
			}
		},
		delete_names_item:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		delete_views_items:{
			ids:{
				type:"ID",
				array:true,
				arrayRequired:false,
				required:true
			}
		},
		delete_views_item:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		delete_views_translations_items:{
			ids:{
				type:"ID",
				array:true,
				arrayRequired:false,
				required:true
			}
		},
		delete_views_translations_item:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			}
		},
		delete_languages_items:{
			ids:{
				type:"ID",
				array:true,
				arrayRequired:false,
				required:true
			}
		},
		delete_languages_item:{
			id:{
				type:"ID",
				array:false,
				arrayRequired:false,
				required:true
			}
		}
	},
	create_names_input:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	create_views_input:{
		user_created:{
			type:"create_directus_users_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_updated:{
			type:"create_directus_users_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		status:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		},
		sort:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		date_created:{
			type:"Date",
			array:false,
			arrayRequired:false,
			required:false
		},
		date_created_func:{
			type:"datetime_functionsInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		date_updated:{
			type:"Date",
			array:false,
			arrayRequired:false,
			required:false
		},
		date_updated_func:{
			type:"datetime_functionsInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		enum:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		},
		name:{
			type:"create_names_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		translations:{
			type:"create_views_translations_input",
			array:true,
			arrayRequired:false,
			required:false
		}
	},
	create_directus_users_input:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		first_name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		last_name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		email:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		password:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		location:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		title:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		description:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		tags:{
			type:"JSON",
			array:false,
			arrayRequired:false,
			required:false
		},
		avatar:{
			type:"create_directus_files_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		language:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		theme:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		tfa_secret:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		status:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		},
		role:{
			type:"create_directus_roles_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		token:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		last_access:{
			type:"Date",
			array:false,
			arrayRequired:false,
			required:true
		},
		last_access_func:{
			type:"datetime_functionsInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		last_page:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		provider:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		},
		external_identifier:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		auth_data:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		email_notifications:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	create_directus_files_input:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		storage:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		},
		filename_disk:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		filename_download:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		},
		title:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		folder:{
			type:"create_directus_folders_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		uploaded_by:{
			type:"create_directus_users_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		uploaded_on:{
			type:"Date",
			array:false,
			arrayRequired:false,
			required:true
		},
		uploaded_on_func:{
			type:"datetime_functionsInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		modified_by:{
			type:"create_directus_users_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		modified_on:{
			type:"Date",
			array:false,
			arrayRequired:false,
			required:true
		},
		modified_on_func:{
			type:"datetime_functionsInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		charset:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		filesize:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		width:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		height:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		duration:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		embed:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		description:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		location:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		tags:{
			type:"JSON",
			array:false,
			arrayRequired:false,
			required:false
		},
		metadata:{
			type:"JSON",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	create_directus_folders_input:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		},
		parent:{
			type:"create_directus_folders_input",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	datetime_functionsInput:{
		year:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		month:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		week:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		day:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		weekday:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		hour:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		minute:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		second:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	create_directus_roles_input:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		},
		icon:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		},
		description:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		ip_access:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:false
		},
		enforce_tfa:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:true
		},
		admin_access:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:true
		},
		app_access:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:true
		},
		users:{
			type:"create_directus_users_input",
			array:true,
			arrayRequired:false,
			required:false
		}
	},
	create_views_translations_input:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		views_id:{
			type:"create_views_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		languages_id:{
			type:"create_languages_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		foo:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:true
		}
	},
	create_languages_input:{
		code:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	update_names_input:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	update_views_input:{
		user_created:{
			type:"update_directus_users_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		user_updated:{
			type:"update_directus_users_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		status:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		sort:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		date_created:{
			type:"Date",
			array:false,
			arrayRequired:false,
			required:false
		},
		date_created_func:{
			type:"datetime_functionsInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		date_updated:{
			type:"Date",
			array:false,
			arrayRequired:false,
			required:false
		},
		date_updated_func:{
			type:"datetime_functionsInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		enum:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"update_names_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		translations:{
			type:"update_views_translations_input",
			array:true,
			arrayRequired:false,
			required:false
		}
	},
	update_directus_users_input:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		first_name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		last_name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		email:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		password:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		location:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		title:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		description:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		tags:{
			type:"JSON",
			array:false,
			arrayRequired:false,
			required:false
		},
		avatar:{
			type:"update_directus_files_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		language:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		theme:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		tfa_secret:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		status:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		role:{
			type:"update_directus_roles_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		token:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		last_access:{
			type:"Date",
			array:false,
			arrayRequired:false,
			required:false
		},
		last_access_func:{
			type:"datetime_functionsInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		last_page:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		provider:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		external_identifier:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		auth_data:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		email_notifications:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	update_directus_files_input:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		storage:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		filename_disk:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		filename_download:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		title:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		type:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		folder:{
			type:"update_directus_folders_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		uploaded_by:{
			type:"update_directus_users_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		uploaded_on:{
			type:"Date",
			array:false,
			arrayRequired:false,
			required:false
		},
		uploaded_on_func:{
			type:"datetime_functionsInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		modified_by:{
			type:"update_directus_users_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		modified_on:{
			type:"Date",
			array:false,
			arrayRequired:false,
			required:false
		},
		modified_on_func:{
			type:"datetime_functionsInput",
			array:false,
			arrayRequired:false,
			required:false
		},
		charset:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		filesize:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		width:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		height:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		duration:{
			type:"Int",
			array:false,
			arrayRequired:false,
			required:false
		},
		embed:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		description:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		location:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		tags:{
			type:"JSON",
			array:false,
			arrayRequired:false,
			required:false
		},
		metadata:{
			type:"JSON",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	update_directus_folders_input:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		parent:{
			type:"update_directus_folders_input",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	update_directus_roles_input:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		icon:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		description:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		},
		ip_access:{
			type:"String",
			array:true,
			arrayRequired:false,
			required:false
		},
		enforce_tfa:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		admin_access:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		app_access:{
			type:"Boolean",
			array:false,
			arrayRequired:false,
			required:false
		},
		users:{
			type:"update_directus_users_input",
			array:true,
			arrayRequired:false,
			required:false
		}
	},
	update_views_translations_input:{
		id:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		views_id:{
			type:"update_views_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		languages_id:{
			type:"update_languages_input",
			array:false,
			arrayRequired:false,
			required:false
		},
		foo:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	},
	update_languages_input:{
		code:{
			type:"ID",
			array:false,
			arrayRequired:false,
			required:false
		},
		name:{
			type:"String",
			array:false,
			arrayRequired:false,
			required:false
		}
	}
}

export const ReturnTypes: Record<string,any> = {
	Query:{
		names:"names",
		names_by_id:"names",
		names_aggregated:"names_aggregated",
		views:"views",
		views_by_id:"views",
		views_aggregated:"views_aggregated",
		views_translations:"views_translations",
		views_translations_by_id:"views_translations",
		views_translations_aggregated:"views_translations_aggregated",
		languages:"languages",
		languages_by_id:"languages"
	},
	names:{
		id:"ID",
		name:"String"
	},
	names_aggregated:{
		group:"JSON",
		avg:"names_aggregated_fields",
		sum:"names_aggregated_fields",
		count:"names_aggregated_fields",
		countDistinct:"names_aggregated_fields",
		avgDistinct:"names_aggregated_fields",
		sumDistinct:"names_aggregated_fields",
		min:"names_aggregated_fields",
		max:"names_aggregated_fields"
	},
	names_aggregated_fields:{
		id:"Float"
	},
	views:{
		user_created:"directus_users",
		user_updated:"directus_users",
		id:"ID",
		status:"String",
		sort:"Int",
		date_created:"Date",
		date_created_func:"datetime_functions",
		date_updated:"Date",
		date_updated_func:"datetime_functions",
		enum:"String",
		name:"names",
		translations:"views_translations"
	},
	directus_users:{
		id:"ID",
		first_name:"String",
		last_name:"String",
		email:"String",
		password:"String",
		location:"String",
		title:"String",
		description:"String",
		tags:"JSON",
		avatar:"directus_files",
		language:"String",
		theme:"String",
		tfa_secret:"String",
		status:"String",
		role:"directus_roles",
		token:"String",
		last_access:"Date",
		last_access_func:"datetime_functions",
		last_page:"String",
		provider:"String",
		external_identifier:"String",
		auth_data:"String",
		email_notifications:"Boolean"
	},
	directus_files:{
		id:"ID",
		storage:"String",
		filename_disk:"String",
		filename_download:"String",
		title:"String",
		type:"String",
		folder:"directus_folders",
		uploaded_by:"directus_users",
		uploaded_on:"Date",
		uploaded_on_func:"datetime_functions",
		modified_by:"directus_users",
		modified_on:"Date",
		modified_on_func:"datetime_functions",
		charset:"String",
		filesize:"Int",
		width:"Int",
		height:"Int",
		duration:"Int",
		embed:"String",
		description:"String",
		location:"String",
		tags:"JSON",
		metadata:"JSON"
	},
	directus_folders:{
		id:"ID",
		name:"String",
		parent:"directus_folders"
	},
	datetime_functions:{
		year:"Int",
		month:"Int",
		week:"Int",
		day:"Int",
		weekday:"Int",
		hour:"Int",
		minute:"Int",
		second:"Int"
	},
	directus_roles:{
		id:"ID",
		name:"String",
		icon:"String",
		description:"String",
		ip_access:"String",
		enforce_tfa:"Boolean",
		admin_access:"Boolean",
		app_access:"Boolean",
		users:"directus_users"
	},
	views_translations:{
		id:"ID",
		views_id:"views",
		languages_id:"languages",
		foo:"String"
	},
	languages:{
		code:"ID",
		name:"String"
	},
	views_aggregated:{
		group:"JSON",
		avg:"views_aggregated_fields",
		sum:"views_aggregated_fields",
		count:"views_aggregated_fields",
		countDistinct:"views_aggregated_fields",
		avgDistinct:"views_aggregated_fields",
		sumDistinct:"views_aggregated_fields",
		min:"views_aggregated_fields",
		max:"views_aggregated_fields"
	},
	views_aggregated_fields:{
		sort:"Float",
		name:"Float"
	},
	views_translations_aggregated:{
		group:"JSON",
		avg:"views_translations_aggregated_fields",
		sum:"views_translations_aggregated_fields",
		count:"views_translations_aggregated_fields",
		countDistinct:"views_translations_aggregated_fields",
		avgDistinct:"views_translations_aggregated_fields",
		sumDistinct:"views_translations_aggregated_fields",
		min:"views_translations_aggregated_fields",
		max:"views_translations_aggregated_fields"
	},
	views_translations_aggregated_fields:{
		id:"Float"
	},
	Mutation:{
		create_names_items:"names",
		create_names_item:"names",
		create_views_items:"views",
		create_views_item:"views",
		create_views_translations_items:"views_translations",
		create_views_translations_item:"views_translations",
		create_languages_items:"languages",
		create_languages_item:"languages",
		update_names_items:"names",
		update_names_item:"names",
		update_views_items:"views",
		update_views_item:"views",
		update_views_translations_items:"views_translations",
		update_views_translations_item:"views_translations",
		update_languages_items:"languages",
		update_languages_item:"languages",
		delete_names_items:"delete_many",
		delete_names_item:"delete_one",
		delete_views_items:"delete_many",
		delete_views_item:"delete_one",
		delete_views_translations_items:"delete_many",
		delete_views_translations_item:"delete_one",
		delete_languages_items:"delete_many",
		delete_languages_item:"delete_one"
	},
	delete_many:{
		ids:"ID"
	},
	delete_one:{
		id:"ID"
	}
}